public enum StatusEffectType
{
    Bleeding,
    Burning,
    Poisoned,
    Slowed,
    Stunned,
    Strong,
    Rage,
    Unsteady,   //Penalty to Dodge
    Agile,
    Blinded,
    Inspired,
    Fortified,
    Regenerating,
    ExposedWeakness,
    DemonicWrath,
    FireVulnerability,
    IceVulnerability,
    PoisonVulnerability,
    ElectricVulnerability,
    DemonsMark,

    Composure,
    DivineProtection,
    Hasty,
    Concealed,
    Marked,
    Undetermined_15,
    Undetermined_14,
    Undetermined_13,
    Undetermined_12,
    Undetermined_11,
    Undetermined_10,
    Undetermined_09,
    Undetermined_08,
    Undetermined_07,
    Undetermined_06,
    Undetermined_05,
    Undetermined_04,
    Undetermined_03,
    Undetermined_02,
    Undetermined_01,

}